---

- name: Install tzdata
  ansible.builtin.apt:
    name: tzdata
    update_cache: true
    cache_valid_time: 3600
    state: present
  tags: ['timezone']
  become: true

- name: Set timezone config
  ansible.builtin.copy:
    content: |
      {{ timezone }}
    dest: /etc/timezone
    mode: '0644'
  tags: ['timezone']
  become: true

- name: Set link to localtime
  ansible.builtin.file:
    state: link
    src: /usr/share/zoneinfo/{{ timezone }}
    dest: /etc/localtime
    force: true
  tags: ['timezone']
  become: true
